/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DirectorRouteImport } from './routes/director'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as MediaIndexRouteImport } from './routes/media.index'
import { Route as MediaSlugRouteImport } from './routes/media.$slug'
import { Route as StaysIndexRouteImport } from './routes/stays.index'
import { Route as StaysSlugRouteImport } from './routes/stays.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorRoute = DirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSlugRoute = MediaSlugRouteImport.update({
  id: '/media/$slug',
  path: '/media/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysIndexRoute = StaysIndexRouteImport.update({
  id: '/stays/',
  path: '/stays/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysSlugRoute = StaysSlugRouteImport.update({
  id: '/stays/$slug',
  path: '/stays/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/director': typeof DirectorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/media/$slug': typeof MediaSlugRoute
  '/stays/$slug': typeof StaysSlugRoute
  '/media/': typeof MediaIndexRoute
  '/stays/': typeof StaysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/director': typeof DirectorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/media/$slug': typeof MediaSlugRoute
  '/stays/$slug': typeof StaysSlugRoute
  '/media': typeof MediaIndexRoute
  '/stays': typeof StaysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/director': typeof DirectorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/media/$slug': typeof MediaSlugRoute
  '/stays/$slug': typeof StaysSlugRoute
  '/media/': typeof MediaIndexRoute
  '/stays/': typeof StaysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/director'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/media/$slug'
    | '/stays/$slug'
    | '/media/'
    | '/stays/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/director'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/media/$slug'
    | '/stays/$slug'
    | '/media'
    | '/stays'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/director'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/media/$slug'
    | '/stays/$slug'
    | '/media/'
    | '/stays/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DirectorRoute: typeof DirectorRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  MediaSlugRoute: typeof MediaSlugRoute
  StaysSlugRoute: typeof StaysSlugRoute
  MediaIndexRoute: typeof MediaIndexRoute
  StaysIndexRoute: typeof StaysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director': {
      id: '/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof DirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$slug': {
      id: '/media/$slug'
      path: '/media/$slug'
      fullPath: '/media/$slug'
      preLoaderRoute: typeof MediaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays/': {
      id: '/stays/'
      path: '/stays'
      fullPath: '/stays/'
      preLoaderRoute: typeof StaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays/$slug': {
      id: '/stays/$slug'
      path: '/stays/$slug'
      fullPath: '/stays/$slug'
      preLoaderRoute: typeof StaysSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DirectorRoute: DirectorRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  MediaSlugRoute: MediaSlugRoute,
  StaysSlugRoute: StaysSlugRoute,
  MediaIndexRoute: MediaIndexRoute,
  StaysIndexRoute: StaysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
